config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  # Existing health check route
  get "up" => "rails/health#show", as: :rails_health_check

  # Articles route with summary generation methods
  resources :articles, only: [:index, :show] do
    # Existing scraped articles route
    get 'scraped/:id', to: 'articles#show_scraped', on: :collection, as: :scraped

    # Summary generation routes (member routes apply to individual articles)
    member do
      post 'generate_summary'
      post 'regenerate_summary'
    end
  end

  # Scraped feeds and articles routes
  resources :scraped_feeds do
    resources :scraped_articles, only: [:index] do
      # Add summary generation for scraped articles
      member do
        post 'generate_summary'
        post 'regenerate_summary'
      end
    end
  end

  # Root route
  root to: "pages#home"

  # Reports routes
  resources :reports, only: [:new, :create, :show] do
    post 'generate', on: :collection, as: :generate
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <!-- These links are available regardless of login state -->
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>

        <!-- Removed the authentication check here -->
        <!-- No need for 'if user_signed_in?' anymore -->

        <li class="nav-item">
          <%= link_to "Generate Report", new_report_path, class: "nav-link" %>
        </li>

        <!-- You can add more links as needed -->
      </ul>
    </div>
  </div>
</div>